version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"   # Expose port 3001 for the backend service
    networks:
      - ngrok-network

  ngrok:
    image: ngrok/ngrok:latest
    command: "start --config=/ngrok/ngrok.yml"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"  # Ngrok's web interface for monitoring tunnels
    volumes:
      - ./ngrok.yml:/ngrok/ngrok.yml  # Mount the ngrok configuration file
    networks:
      - ngrok-network

networks:
  ngrok-network:
    driver: bridge
